apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nap-ingress
  namespace: nap
  annotations:
    appprotect.f5.com/app-protect-policy: "nap-ingress"
    appprotect.f5.com/app-protect-enable: "True"
    appprotect.f5.com/app-protect-security-log-enable: "True"
    appprotect.f5.com/app-protect-security-log: "logconf"
    appprotect.f5.com/app-protect-security-log-destination: "syslog:server=10.1.20.20:8515"
spec:
  ingressClassName: nginx-plus
  rules:
  - host: nap-ingress.f5k8s.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webapp-svc
            port:
              number: 80